version: '3.8'

services:
  db:
    image: mysql
    container_name: webservice_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
  java:
    image: migueldoctor/cosmos-gitlabci-jdk8-maven-gradle
    container_name: webservice_server
    command: mvn clean install exec:java -Dexec.args="8080"
    working_dir: /usr/comp_dist/
    restart: always
    ports:
      - 9001:8080
    volumes:
      - .:/usr/comp_dist/
